### ISSUE TITLE
IsSelfPromotion

### ISSUE THREAD

**Issue by MikeVL** [KokocGroup/OrdMediascoutClientAPI#6]
По запросу 

`creatives = api.get_creatives(GetCreativesWebApiDto())`

Выдаёт ошибку:

```
pydantic.error_wrappers.ValidationError: 244 validation errors for ParsingModel[list[ord_mediascout_client.models.CreativeWebApiDto]]
__root__ -> 0 -> IsSelfPromotion
  extra fields not permitted (type=value_error.extra)
__root__ -> 1 -> IsSelfPromotion
  extra fields not permitted (type=value_error.extra)
__root__ -> 2 -> IsSelfPromotion
  extra fields not permitted (type=value_error.extra)
__root__ -> 3 -> IsSelfPromotion
```

**Comment by a-ruzin** [comment]
да, бывает что API медиаскаута обновляется "внезапно", а мы не успеваем его править.
Еще есть момент, что у них API на тестовом стенде (demo.mediascout.ru) и проде (lk.demo.mediascout.ru) различаются, а у нас библиотека одной версии. Делать поддержку одновременно нескольких их версий через параметр в нашей либе, мы посчитали сложным, поэтому во время перехода с одной версии API на другую что-то может "сыпаться"
